### ISSUE TITLE
FormWidget: Translated nested value set to property[subproperty]

### ISSUE THREAD

**Issue by StevenLangbroek** [mojotech/pioneer#208]
Useful for larger forms.

```
validSignup =
  user:
    firstname: 'John'
    lastname: 'Doe'
    email: 'johndoe@gmail.com'
  company:
    name: 'Mojotech'
    url: 'http://www.mojotech.com'

new FormWidget().submitWith(validSignup)
```
